version: '3.8'

services:
  frontend:
    build:
      context: ./TradingAI-Frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend

  backend:
    build:
      context: ./TradingAI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - SPRING_DATASOURCE_USERNAME=${username}
      - SPRING_DATASOURCE_PASSWORD=${password}
      - GOOGLE_CLIENT_ID=${client_id}
      - GOOGLE_CLIENT_SECRET=${client_secret}

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${username}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: tradingai
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
      - ./TradingAI-Frontend/dist/TradingAI-Frontend:/usr/share/nginx/html:ro

volumes:
  db_data: