version: '3.8'

services:
  frontend:
    build:
      context: ./TradingAI-Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./TradingAI
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_VAULT_TOKEN=${SPRING_CLOUD_VAULT_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - vault

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

volumes:
  db_data: